### PR TITLE
Django 1.11+ compatibility for tests

### PR DESCRIPTION
**Pull request by supervacuo**
Get tests passing on Django 1.11 and 2.0

(Also includes #20 because otherwise tests still wouldn't work)

### CODE REVIEW

**Comment by ambv** [comment]
This looks promising, do you know what you need to change to make Python 3.7 available on Travis?

**Comment by supervacuo** [comment]
@ambv looks like [`tox-travis`](https://github.com/tox-dev/tox-travis) could help. I'll try it out now.

**Comment by ambv** [comment]
So what is the oldest version of Django that we will be supporting with your changes?

**Comment by supervacuo** [comment]
Tests are passing on Django 1.10.3; there's maybe an argument for only supporting 1.11+ though, as [1.10 is end-of-life](https://www.djangoproject.com/download/#supported-versions)

**Pull request merged**
